import React, { useState } from 'react';
import { CheckCircle2, ChevronDown, ChevronRight, ClipboardList, Radio, RotateCcw } from 'lucide-react';
import { CHRISTMAS_OB_TEST, PROGRAMME_RECIPES } from '../../data/radioProgrammeTemplates';

const KEY = 'farmers-table-radio-recipes-v1';
const load = (): Record<string, boolean> => { try { return JSON.parse(localStorage.getItem(KEY) || '{}'); } catch { return {}; } };

export const RadioBuildRecipes: React.FC = () => {
  const [open, setOpen] = useState<string | null>(PROGRAMME_RECIPES[0].id);
  const [checked, setChecked] = useState<Record<string, boolean>>(load);
  const toggle = (id: string) => setChecked(current => { const next = { ...current, [id]: !current[id] }; localStorage.setItem(KEY, JSON.stringify(next)); return next; });
  const reset = () => { localStorage.removeItem(KEY); setChecked({}); };
  return <section className="space-y-5">
    <div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-brand-olive text-xs font-bold uppercase tracking-widest"><ClipboardList size={15}/> Programme recipes</div><h2 className="text-2xl font-serif mt-1">Build each type once, then reuse it</h2><p className="text-sm text-brand-ink/55 mt-1 max-w-3xl">These are the repeatable programme patterns. The audio itself is always real material or an obvious placement holder.</p></div><button onClick={reset} className="text-xs font-bold px-3 py-2 rounded-xl bg-brand-cream flex items-center gap-2"><RotateCcw size={13}/> Reset checks</button></div>
    <div className="space-y-2">{PROGRAMME_RECIPES.map(recipe => <div key={recipe.id} className="rounded-2xl border border-brand-olive/10 bg-white overflow-hidden"><button onClick={() => setOpen(open === recipe.id ? null : recipe.id)} className="w-full p-4 flex items-center gap-4 text-left"><Radio className="text-brand-olive shrink-0" size={20}/><div className="flex-1"><div className="font-bold">{recipe.name}</div><div className="text-xs text-brand-ink/45 mt-1">{recipe.durationMinutes} minutes · {recipe.purpose}</div></div>{open === recipe.id ? <ChevronDown/> : <ChevronRight/>}</button>{open === recipe.id && <div className="px-4 pb-5"><div className="grid md:grid-cols-2 gap-2">{recipe.sequence.map((step, i) => { const id = `${recipe.id}-${i}`; return <button key={id} onClick={() => toggle(id)} className={`rounded-xl p-3 text-left flex items-start gap-3 text-sm ${checked[id] ? 'bg-emerald-50' : 'bg-brand-cream'}`}><span className="text-xs font-bold text-brand-ink/35 mt-0.5">{i + 1}</span>{checked[id] ? <CheckCircle2 size={17} className="text-brand-olive shrink-0"/> : <span className="w-[17px] h-[17px] rounded-full border-2 border-brand-olive/20 shrink-0"/>}<span className="font-medium">{step}</span></button>; })}</div><p className="text-xs text-brand-ink/45 mt-3">{recipe.notes}</p></div>}</div>)}</div>

    <div className="rounded-[28px] bg-brand-ink text-brand-cream p-6 md:p-7"><div className="flex items-start gap-3"><Radio className="mt-1"/><div><div className="text-xs uppercase tracking-widest text-brand-cream/50 font-bold">Special test</div><h3 className="text-2xl font-serif mt-1">🎄 {CHRISTMAS_OB_TEST.title}</h3><p className="text-sm text-brand-cream/60 mt-2">Asset ID: <strong className="text-brand-cream">{CHRISTMAS_OB_TEST.id}</strong>. This is a rehearsal checklist, not a fictional broadcast.</p></div></div><div className="grid lg:grid-cols-3 gap-4 mt-6">{[['Before you leave', CHRISTMAS_OB_TEST.before], ['While live', CHRISTMAS_OB_TEST.live], ['If something goes wrong', CHRISTMAS_OB_TEST.recovery], ['When you get home', CHRISTMAS_OB_TEST.after]].map(([title, items]) => <div key={title as string} className="rounded-2xl bg-white/10 p-4"><h4 className="font-bold">{title as string}</h4><ul className="mt-3 space-y-2">{(items as string[]).map(item => <li key={item} className="text-sm text-brand-cream/70 flex gap-2"><span>•</span><span>{item}</span></li>)}</ul></div>)}</div></div>
  </section>;
};
