-- SUPERSEDED — intentionally left as a no-op.
--
-- This file was "Step 2 of 2" of the original two-file directory build:
--   20260317_create_directory_listings_table.sql  (structure)
--   20260317_seed_directory_listings.sql          (this file, the seed)
--
-- A second, all-in-one file — 20260317_create_directory_listings.sql —
-- creates the same table AND carries the same 145 producer rows. When the
-- structure half of the pair was retired (see the header of
-- 20260317_create_directory_listings_table.sql), this seed half was left
-- active, so BOTH files ran and both inserted the same 145 producers.
--
-- Their `ON CONFLICT DO NOTHING` did not prevent it. There is no unique
-- constraint on `name`, so the only arbiter is the primary key, and each
-- INSERT supplies a fresh gen_random_uuid(). The conflict never fires.
--
-- Measured on a clean build of the full migration set before this change:
--   select count(*) from directory_listings;                    -> 290
--   select count(distinct lower(btrim(name))) ...;              -> 145
-- Every producer was present exactly twice.
--
-- That is also why 20260828_tft_permissions_rls.sql could never create
-- its unique index on lower(btrim(name)): it correctly refuses to run
-- while duplicates exist, and the duplicates were created two migrations
-- earlier by this file. Retiring this seed lets that index build, which
-- makes the remaining seed genuinely idempotent from then on.
--
-- 20260317_create_directory_listings.sql is the single seed of record.
-- The 145 producer records are unchanged and are NOT deleted here.
--
-- Left in place rather than deleted so environments that recorded this
-- filename in their migration history do not see it disappear — the same
-- treatment given to 20260317_create_directory_listings_table.sql.

select 1;
